spring:
  cloud:
    function:
      definition: notification;maskedRecords

    stream:
      bindings:
        notification-in-0:
          destination: pos-topic

        notification-out-0:
          destination: loyalty-topic

        maskedRecords-in-0:
          destination: pos-topic

        maskedRecords-out-0:
          destination: hadoop-sink-topic

#      kafka:
#        bindings:
#          process-in-0:
#            consumer:
#              configuration:
#                value:
#                  deserializer: org.springframework.kafka.support.serializer.DelegatingDeserializer

        streams:
          binder:
            brokers:
              - localhost:9091
              - localhost:9092

            functions:
              notification:
                applicationId: notification-loyalty

              maskedRecords:
                applicationId:  masked-hadoop-records

            configuration:
              schema:
                registry:
                  url:  http://localhost:80801

          bindings:
            notification-out-0:
              producer:
                keySerde: CustomKeySerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            maskedRecords-out-0:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde